@endpoint= https://cjuc795mtc.execute-api.us-west-2.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location":"Oregon",
    "name":"Best location"
}
###