@endpoint= https://cjuc795mtc.execute-api.us-west-2.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces
###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location":"Oregon",
    "name":"Best location"
}
###
PUT {{endpoint}}/spaces?spaceId=d2b7b307-44d5-4f99-956f-ca1c333ca2a4
Content-Type: application/json

{
    "location": "Updated Location ggg"
}
###


DELETE {{endpoint}}/spaces?spaceId=d2b7b307-44d5-4f99-956f-ca1c333ca2a4
###

GET {{endpoint}}/spaces?location=Oregon
###
